version: '3.6'

services:
  db:
    image: supabase/postgres:latest
    container_name: supabase_db
    env_file:
      - .env
    ports:
      - "5432:5432"

  api:
    image: supabase/gotrue:latest
    container_name: supabase_api
    env_file:
      - .env
    ports:
      - "9999:9999"

  auth:
    image: supabase/auth:latest
    container_name: supabase_auth
    env_file:
      - .env

  storage:
    image: supabase/storage:latest
    container_name: supabase_storage
    env_file:
      - .env
    ports:
      - "5000:5000"
